### ISSUE TITLE
The extension is said to be removed from the firefox store. 

### ISSUE THREAD

**Issue by GintokiHub** [DanielKamkha/GameDeals#3]
Was this intentional? Any idea what caused this and wheter it will be up there again?

**Comment by DanielKamkha** [comment]
I de-listed the extension from AMO. It accumulated a bunch of bugs as websites and API changed over time. And it proved to be unpopular (in comparison to my other FF extensions).

Since my resources and time are limited, I decided to pull the plug for GameDeals extension.

My code is licensed under MIT license, so please feel free to fork GameDeals , relist it under your name and support it further, if you want/can.
